### ISSUE TITLE
Předseda KrP je členem ReV

### ISSUE THREAD

**Issue by kubicek** [svobodni/party_registry#12]
Spolu s předsednictvím KrP má bát automaticky svázáno členství v ReV.

**Comment by zvara** [comment]
Rozhodně jsem pro to, aby to spojoval Registr, protože jde o definice členství v ReVu. Člen ReP a předseda KrP jsou automaticky členy ReVu. Pokud to bude řešit Registr, bude to automaticky správně fungovat ve všech systémech. Kdybych to nastavil v SMF (mohl bych), fungovalo by to jen pro fórum.

**Comment by kubicek** [comment]
Registr ano, jen řeším, jestli to udělat trikem a do /profile.json přidat roli ReV pokud je předseda KrP nebo jestli jim všem dávat dvě role přímo v databázi.

Rozdíl bude právě v tom, že když jim dám role v databázi, budou se zobrazovat i jako členové ReVu v exportu /bodies.json a budou se zobrazovat na webu, což do teď nebylo (na webu jsme měli jen přímo volené členy ReVu).
