### ISSUE TITLE
Řadit kraje abecedně

### ISSUE THREAD

**Issue by AloisSeckar** [svobodni/party_registry#15]
Aktuálně jsou kraje v registru (minimálně na "osobním rozcestníku") řazené trochu divně - první Praha, potom české a potom moravské kraje...je tu návrh řadit je raději abecedně, což mi přijde rozumnější, protože je to determinované

**Comment by kubicek** [comment]
Kraje jsou tříděny podle identifikátoru nuts3, pro Prahu je to dobré :)

Předělám
