### ISSUE TITLE
Export datábaze - rozesílání časopisu Beran

### ISSUE THREAD

**Issue by peepo68** [svobodni/party_registry#17]
Požadavků na přehledy, filtrování a exporty databáze bude více. Tady je jeden z nich:

- požadavek na "jednotlačítkový" export zasílacích adres členů a příznivců pro časopis Beran. Základ jsou adresy nebo korespondenčí adresy. Ale měly by být vyjmuti ti, kteří se z odběru tištěného časopisu aktivně (přes kancelář nebo editací svého profilu) odhlásili.

**Comment by peepo68** [comment]
Doplňuji - související úkol je tedy umožnit v profilu odhlásit se z odběru tištěného Berana. Mám na to založit nové Issue nebo to stačí takto?

**Comment by kubicek** [comment]
V jakém formátu má export být?

CSV/XLS, jaké sloupce, co v nich?

Možnost odhlásit od Berana zapracuji. Nějaký nápad, kam to dát v profilu? Novou stránku do menu, nadepsanou "Beran"?

**Comment by kubicek** [comment]
Možnost odhlášení Berana souvisí s #5

**Comment by kubicek** [comment]
uzavřeno v ac9b5637dd97145412e1172b2db3709452fb6a2e
