### ISSUE TITLE
Příznak "nezasílat Berana"

### ISSUE THREAD

**Issue by AloisSeckar** [svobodni/party_registry#26]
Všichni členové a příznivci by měli mít možnost odmítnout zasílání tištěné podoby magazínu Beran. Informace o odmítnutí musí být k dispozici v registru, aby registr mohl jednoduše poskytnout seznam adres těch, kteří Berana chtějí a nebylo třeba adresy filtrovat ručně.

**Comment by peepo68** [comment]
Kancelář by měla mít možnost nastavit příznak "nezasílat Beran" nastavit i u kontatků, u kterých se (opakovaně) projeví "nedoručená zásilka".

I když je úkolem kanceláře, aby takových adres v databzi bylo co nejméně.

**Comment by kubicek** [comment]
Vyřešeno v 2dee9eff27362cffca971af977dab209689a2b5b a 7fb609a3162da9d974c4bd29ee6a44d04c1638e4
