### ISSUE TITLE
Přístup volební komise 

### ISSUE THREAD

**Issue by dqd** [svobodni/party_registry#30]
Na začátku tohoto týdne volební komisi (nebo minimálně předsedovi a místopředsedovi) přestal fungovat přístup k údajům členům strany. Odkaz https://registr.svobodni.cz/people.json vrací pouze údaje o přihlášeném člověku, podobně kliknutí na detail (např. https://registr.svobodni.cz/people/342) zobrazí pouze chybovou hlášku „Access Denied“.

Volební komise potřebuje přístup k údajům členů pro hromadné rozesílání upozornění týkajících se voleb.

**Comment by kubicek** [comment]
Opraveno ve 4497565fb71c5c5abd141a54033db2af2fc3fd4b
