### ISSUE TITLE
Přidání atributu „cv“ do people.json

### ISSUE THREAD

**Issue by dqd** [svobodni/party_registry#32]
Abychom mohli vyřešit https://github.com/svobodni/ballot_box/issues/22, potřebovali bychom rozšířit výpis osob (`people.json`) o atribut obsahující odkaz na CV (nebo `null` v případě, když ho nemá) u každé osoby.

**Comment by kubicek** [comment]
Registr neví, kdo má nahraný životopis a kdo ne, protože některé jsou ještě ve files. Bude vyřešeno po domigrování.

**Comment by me2d09** [comment]
Myslím, že je to vyřešeno, protože to u některých kandidátů životopis neukazuje.

**Comment by me2d09** [comment]
![image](https://user-images.githubusercontent.com/7137805/68013341-e9d23800-fc8c-11e9-9297-298046f708a7.png)
