### ISSUE TITLE
Chyba 500 na stránce contacts.json

### ISSUE THREAD

**Issue by dqd** [svobodni/party_registry#43]
Když otevřu URL https://registr.svobodni.cz/contacts.json, napíše se mi tato chybová hláška: ```{"status":"500","error":"Internal Server Error"}```

**Comment by kubicek** [comment]
Na té url to bývalo? Hlásí to, že tam vůbec není šablona. 

```
An ActionView::MissingTemplate occurred in contacts#index:
Missing template contacts/index, application/index with {:locale=>[:cs], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder, :prawn]}. 
```

**Comment by dqd** [comment]
Tady čtu, že by mělo existovat `GET /contacts.json`: https://github.com/svobodni/party_registry/blob/master/app/controllers/contacts_controller.rb#L6

**Comment by kubicek** [comment]
Aha. Tak bohužel. Ten comment je generovaný, chybí tam šablona pro zobrazení.

**Comment by dqd** [comment]
OK, rozumím, zavírám.
